export const VERTICAL_2COLUM = 0
export const HORIZONTAL_2COLUMN = 1
export const HORIZONTAL_LAYOUT = "HORIZONTAL_LAYOUT"
export const VERTICAL_LAYOUT = "VERTICAL_LAYOUT"
export const SELECTED_APP = "SELECTED_APP"